server:
  port: 8090


#DB Config
spring:
  profiles:
    active: dev

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver

    druid:
      filters: config,stat,wall
      initialSize: 20
      minIdle: 10
      maxActive: 100
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: feverwind
#      allow: 127.0.0.1


  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML
    cache: false

  liquibase:
    change-log: classpath:/liquibase/master.xml
    check-change-log-location: true
    enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xsh.blog.dao