server:
  port: 8090

#DB Config
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.3.29.163:3306/blog?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: root
    password: root
    initialSize: 20
    minIdle: 10
    maxActive: 100
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5
    cache: false

liquibase:
  change-log: classpath:/liquibase/master.xml

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xsh.blog.dao